namespace OctoglowSender;
public static class AppStrings
{
    private static string _language = ResolveLanguage(ConfigStore.Load().Language);
    public static bool IsEnglish => _language == "en";
    public static event EventHandler? LanguageChanged;
    private static readonly Dictionary<string, (string ro, string en)> Text = new()
    {
        ["clock.screenWaiting"] = ("Se așteaptă conexiunea cu ceasul", "Waiting for the clock"),
        ["clock.screenOffline"] = ("Ceasul nu răspunde", "The clock isn't responding"),
        ["clock.screenUnsupported"] = ("Firmware-ul ceasului nu are această funcție. Actualizați-l.", "The clock's firmware doesn't support this. Update it."),
        ["clock.screenOff"] = ("Ecranul ceasului e stins", "The clock's display is off"),
        ["app.title"] = ("Octoglow Connect", "Octoglow Connect"),
        ["nav.home"] = ("Acasă", "Home"), ["nav.scan"] = ("Scanează dispozitive", "Scan for devices"), ["nav.scanning"] = ("Se caută…", "Scanning…"), ["nav.devices"] = ("Dispozitive", "Devices"),
        ["nav.connection"] = ("Conexiune", "Connection"), ["nav.customize"] = ("Customize", "Customize"), ["nav.settings"] = ("Setări", "Settings"), ["nav.logs"] = ("Jurnal activitate", "Activity log"), ["nav.about"] = ("Despre", "About"),
        ["device.online"] = ("Online", "Online"), ["device.offline"] = ("Offline", "Offline"),
        ["device.connected"] = ("Conectat", "Connected"), ["device.disconnected"] = ("Deconectat", "Disconnected"),
        ["hub.title"] = ("Dispozitivele tale Octoglow", "Your Octoglow devices"),
        ["hub.subtitle"] = ("Octoglow Connect detectează automat ceasurile din rețeaua locală și dispozitivele Macro conectate prin USB.", "Octoglow Connect automatically detects clocks on your local network and Macro devices connected over USB."),
        ["hub.deskClock"] = ("Desk Clock online", "Desk Clocks online"), ["hub.macro"] = ("Macro online", "Macros online"),
        ["hub.devicesTitle"] = ("Toate dispozitivele", "All devices"), ["hub.devicesSubtitle"] = ("Dispozitivele detectate sau adăugate manual apar liber în acest spațiu.", "Detected and manually added devices appear freely in this space."),
        ["hub.emptyTitle"] = ("Nu am găsit încă niciun dispozitiv", "No devices found yet"), ["hub.emptyDescription"] = ("Conectează Octoglow Macro prin USB, pornește o scanare sau folosește butonul + pentru a adăuga manual un Desk Clock.", "Connect Octoglow Macro over USB, run a scan, or use the + button to add a Desk Clock manually."),
        ["hub.addDevice"] = ("Adaugă un dispozitiv", "Add a device"), ["hub.addDeviceQuestion"] = ("Ce device dorești să adaugi?", "Which device would you like to add?"), ["hub.continue"] = ("Continuă", "Continue"), ["hub.cancel"] = ("Anulează", "Cancel"),
        ["hub.addClockTitle"] = ("Adaugă Octoglow Desk Clock", "Add Octoglow Desk Clock"), ["hub.manualClockDescription"] = ("Introdu adresa ceasului care nu a putut fi detectat automat. Va apărea imediat în lista de dispozitive.", "Enter the address of the clock that could not be detected automatically. It will appear in the device list immediately."), ["hub.add"] = ("Adaugă", "Add"),
        ["clock.title"] = ("Octoglow Desk Clock", "Octoglow Desk Clock"), ["clock.subtitle"] = ("Informații, conexiune și acces la panoul de configurare al ceasului.", "Device information, sender connection, and access to the clock control panel."),
        ["clock.overviewTab"] = ("Prezentare generală", "Overview"), ["clock.integrationsTab"] = ("Integrări", "Integrations"), ["clock.activityTab"] = ("Jurnal activitate", "Activity log"),
        ["clock.integrationsTitle"] = ("Integrări Desk Clock", "Desk Clock integrations"), ["clock.integrationsSubtitle"] = ("Controlează datele pe care Octoglow Connect le trimite către acest ceas.", "Control the data Octoglow Connect sends to this clock."), ["clock.restoreIntegrations"] = ("Restabilește integrările implicite", "Restore integration defaults"),
        ["clock.model"] = ("Model", "Model"), ["clock.transport"] = ("Conexiune", "Connection"), ["clock.address"] = ("Adresă detectată", "Detected address"),
        ["clock.connectionTitle"] = ("Conexiune Octoglow Sender", "Octoglow Sender connection"), ["clock.connectionDescription"] = ("Datele sunt salvate local. După autentificare, notificările, media și telemetria ETS2 sunt trimise automat către acest ceas.", "Credentials are stored locally. After sign-in, notifications, media, and ETS2 telemetry are sent automatically to this clock."),
        ["clock.openPanel"] = ("Deschide setările device-ului", "Open device settings"), ["clock.detected"] = ("Detectat", "Detected"),
        ["clock.offlineTitle"] = ("Ceasul nu răspunde momentan", "The clock is not responding"), ["clock.offlineMessage"] = ("Poți modifica adresa salvată sau poți porni o scanare din meniul din stânga.", "You can edit the saved address or start a scan from the left menu."),
        ["clock.invalidAddressTitle"] = ("Adresă invalidă", "Invalid address"), ["clock.invalidAddressMessage"] = ("Introdu un IP sau hostname valid și un port între 1 și 65535.", "Enter a valid IP address or hostname and a port between 1 and 65535."),
        ["macro.title"] = ("Octoglow Macro", "Octoglow Macro"), ["macro.subtitle"] = ("Informații USB și test live pentru cele 7 taste și encoder.", "USB information and live testing for the seven keys and encoder."),
        ["macro.product"] = ("Identitate HID", "HID identity"), ["macro.transport"] = ("Transport", "Transport"), ["macro.usbRevision"] = ("Revizie USB", "USB revision"),
        ["macro.supportTitle"] = ("Suport Macro în dezvoltare", "Macro support in progress"), ["macro.supportMessage"] = ("Detecția și previzualizarea live funcționează. Mapările sunt afișate read-only până când firmware-ul oferă un protocol sigur de configurare.", "Detection and live input preview work. Mappings remain read-only until the firmware exposes a safe configuration protocol."),
        ["macro.liveTitle"] = ("Test live", "Live test"), ["macro.liveDescription"] = ("Apasă tastele sau rotește encoderul; elementul corespunzător se evidențiază fără a confunda input-ul cu tastatura normală.", "Press keys or rotate the encoder; the matching control highlights without mixing input from your regular keyboard."),
        ["macro.mappingsTitle"] = ("Mapări actuale din firmware", "Current firmware mappings"), ["macro.mappingsDescription"] = ("Aceste acțiuni sunt trimise direct de firmware și nu pot fi schimbate încă din aplicație.", "These actions are sent directly by the firmware and cannot yet be changed from the app."),
        ["connection.title"] = ("Conexiune", "Connection"), ["connection.ip"] = ("Adresă IP", "IP address"), ["connection.port"] = ("Port", "Port"), ["connection.user"] = ("Utilizator", "Username"), ["connection.password"] = ("Parolă", "Password"), ["connection.start"] = ("Pornește și salvează", "Start and save"), ["connection.stop"] = ("Oprește", "Stop"), ["connection.starting"] = ("Pornire...", "Starting..."), ["connection.stopped"] = ("Oprit.", "Stopped."), ["connection.connecting"] = ("Se conectează…", "Connecting…"), ["connection.connected"] = ("Conectat", "Connected"), ["connection.failed"] = ("Conexiune eșuată", "Connection failed"), ["connection.disconnected"] = ("Deconectat", "Disconnected"),
        ["settings.title"] = ("Setări aplicație", "App settings"), ["settings.appSubtitle"] = ("Aspect și comportament general pentru Octoglow Connect.", "Appearance and general behavior for Octoglow Connect."), ["settings.appearance"] = ("Aspect și limbă", "Appearance and language"), ["settings.language"] = ("Limbă", "Language"), ["settings.language.system"] = ("Sistem implicit", "System default"), ["settings.theme"] = ("Temă", "Theme"), ["settings.theme.system"] = ("Sistem implicit", "System default"), ["settings.theme.light"] = ("Luminos", "Light"), ["settings.theme.dark"] = ("Întunecat", "Dark"), ["settings.backdrop"] = ("Material fundal", "Backdrop material"), ["settings.backdrop.none"] = ("Fără", "None"), ["settings.backdrop.mica"] = ("Mica", "Mica"), ["settings.backdrop.micaalt"] = ("Mica Alt", "Mica Alt"), ["settings.backdrop.acrylic"] = ("Acrylic", "Acrylic"), ["settings.appBehavior"] = ("Comportament aplicație", "App behavior"), ["settings.startup"] = ("Pornește odată cu Windows", "Run at Windows startup"), ["settings.tray"] = ("Minimizează în zona de notificări", "Minimize to notification area"), ["settings.nowPlaying"] = ("Video / Muzică în redare", "Video / Music now playing"), ["settings.nowPlayingDescription"] = ("Configurează ce aplicații sunt tratate ca surse video sau muzică pentru tile-ul Now Playing.", "Configure which apps are treated as video or music sources for the Now Playing tile."), ["settings.video"] = ("Playere video (un nume pe rând)", "Video players (one name per line)"), ["settings.music"] = ("Playere muzică (un nume pe rând)", "Music players (one name per line)"), ["settings.save"] = ("Salvează setările", "Save settings"),
        ["settings.devices"] = ("Dispozitive salvate", "Saved devices"), ["settings.devicesDescription"] = ("Elimină dispozitivele din Home și uită adresa Desk Clock salvată. Dispozitivele detectate pot reapărea la următoarea scanare.", "Remove devices from Home and forget the saved Desk Clock address. Detected devices can reappear during the next scan."), ["settings.clearDevices"] = ("Șterge toate dispozitivele", "Remove all devices"),
        ["settings.clearDevicesConfirmTitle"] = ("Ștergi toate dispozitivele?", "Remove all devices?"), ["settings.clearDevicesConfirmDescription"] = ("Lista din Home și adresa Desk Clock salvată vor fi șterse. Celelalte preferințe rămân neschimbate.", "The Home device list and saved Desk Clock address will be cleared. Other preferences remain unchanged."),
        ["logs.title"] = ("Jurnal Desk Clock", "Desk Clock activity"), ["logs.description"] = ("Autentificarea, notificările, media și telemetria ETS2 trimise către ceas apar aici în timp real.", "Authentication, notifications, media, and ETS2 telemetry sent to the clock appear here in real time."),
        ["activity.last"] = ("Ultima activitate", "Latest activity"), ["activity.empty"] = ("Încă nu există activitate.", "No activity yet."),
        ["customize.title"] = ("Setări Desk Clock", "Desk Clock settings"), ["customize.description"] = ("Panoul dispozitivului se deschide folosind datele salvate la Conexiune.", "The device panel opens using the credentials saved in Connection."), ["customize.reload"] = ("Reîncarcă", "Reload"), ["customize.back"] = ("Înapoi la dispozitiv", "Back to device"), ["customize.missing"] = ("Salvează mai întâi o adresă IP validă în pagina Conexiune.", "Save a valid IP address in the Connection page first."), ["customize.errorTitle"] = ("Panoul nu este disponibil", "Panel unavailable"), ["customize.error"] = ("Nu s-a putut încărca panoul device-ului.", "The device panel could not be loaded.")
    };
    public static string Get(string key) => Text.TryGetValue(key, out var value) ? (_language == "en" ? value.en : value.ro) : key;
    public static void SetLanguage(string language) { _language = ResolveLanguage(language); LanguageChanged?.Invoke(null, EventArgs.Empty); }
    /// <summary>Turns a stored language ("system" | "ro" | "en") into the effective "ro"/"en" used for display text.</summary>
    private static string ResolveLanguage(string language) => language switch
    {
        "en" => "en",
        "ro" => "ro",
        _ => System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("ro", StringComparison.OrdinalIgnoreCase) ? "ro" : "en"
    };
}
